In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("weather_data.csv")
df

     Outlook  Temp Humidity Windy Play
0      Rainy   Hot     High     f   no
1      Rainy   Hot     High     t   no
2   Overcast   Hot     High     f  yes
3      Sunny  Mild     High     f  yes
4      Sunny  Cool   Normal     f  yes
5      Sunny  Cool   Normal     t   no
6   Overcast  Cool   Normal     t  yes
7      Rainy  Mild     High     f   no
8      Rainy  Cool   Normal     f  yes
9      Sunny  Mild   Normal     f  yes
10     Rainy  Mild   Normal     t  yes
11  Overcast  Mild     High     t  yes
12  Overcast   Hot   Normal     f  yes
13     Sunny  Mild     High     t   no

In [28]:
#NaiveBayes project (Weather Prediction)
#Required Modules
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

In [29]:
#Reading CSV files
df = pd.read_csv("weather_data.csv")
df

     Outlook  Temp Humidity Windy Play
0      Rainy   Hot     High     f   no
1      Rainy   Hot     High     t   no
2   Overcast   Hot     High     f  yes
3      Sunny  Mild     High     f  yes
4      Sunny  Cool   Normal     f  yes
5      Sunny  Cool   Normal     t   no
6   Overcast  Cool   Normal     t  yes
7      Rainy  Mild     High     f   no
8      Rainy  Cool   Normal     f  yes
9      Sunny  Mild   Normal     f  yes
10     Rainy  Mild   Normal     t  yes
11  Overcast  Mild     High     t  yes
12  Overcast   Hot   Normal     f  yes
13     Sunny  Mild     High     t   no

In [30]:
#Encoding the strings to Numericals
outlook_at=LabelEncoder()
Temp_at=LabelEncoder()
Hum_at=LabelEncoder()
win_at=LabelEncoder()

In [31]:
#Dropping the target variable and make it is as newframe
inputs=df.drop('Play',axis='columns')
target=df['Play']
target.values

array(['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes',
       'yes', 'yes', 'yes', 'no'], dtype=object)

In [32]:
#Creating the new dataframe
inputs['outlook_n']= outlook_at.fit_transform(inputs['Outlook'])
inputs['Temp_n']= outlook_at.fit_transform(inputs['Temp'])
inputs['Hum_n']= outlook_at.fit_transform(inputs['Humidity'])
inputs['win_n']= outlook_at.fit_transform(inputs['Windy'])
inputs

     Outlook  Temp Humidity Windy  outlook_n  Temp_n  Hum_n  win_n
0      Rainy   Hot     High     f          1       1      0      0
1      Rainy   Hot     High     t          1       1      0      1
2   Overcast   Hot     High     f          0       1      0      0
3      Sunny  Mild     High     f          2       2      0      0
4      Sunny  Cool   Normal     f          2       0      1      0
5      Sunny  Cool   Normal     t          2       0      1      1
6   Overcast  Cool   Normal     t          0       0      1      1
7      Rainy  Mild     High     f          1       2      0      0
8      Rainy  Cool   Normal     f          1       0      1      0
9      Sunny  Mild   Normal     f          2       2      1      0
10     Rainy  Mild   Normal     t          1       2      1      1
11  Overcast  Mild     High     t          0       2      0      1
12  Overcast   Hot   Normal     f          0       1      1      0
13     Sunny  Mild     High     t          2       2      0      1

In [33]:
#Dropping the string values
inputs_n=inputs.drop(['Outlook','Temp','Humidity','Windy'],axis='columns')
inputs_n.values

array([[1, 1, 0, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 0],
       [2, 2, 0, 0],
       [2, 0, 1, 0],
       [2, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 2, 0, 0],
       [1, 0, 1, 0],
       [2, 2, 1, 0],
       [1, 2, 1, 1],
       [0, 2, 0, 1],
       [0, 1, 1, 0],
       [2, 2, 0, 1]])

In [34]:
#Applying the Gaussian naivebayes
classifier = GaussianNB()
classifier.fit(inputs_n.values,target.values)

GaussianNB()

In [35]:
#85% accuracy 
classifier.score(inputs_n.values,target.values)

0.8571428571428571

In [36]:
#Prediction
classifier.predict([[0,0,0,1]])

array(['yes'], dtype='<U3')